export enum IconNames {
  TS = 'TypeScript',
  JAVASCRIPT = 'Javascript',
  ANGULAR = 'Angular',
  RXJS = 'RxJS',
  NGRX = 'NGRX',
  VUE = 'VueJS',
  NUXT = 'Nuxt',
  PINIA = 'Pinia',
  SCSS = 'SCSS',
  TAILWIND = 'Tailwind',
  GRAPHQL = 'graphQL',
  REST = 'REST',
  HTML = 'HTML',
  CSS = 'CSS',
}
