export enum IconNames {
  ANGULAR = 'Angular',
  JAVASCRIPT = 'Javascript',
  GRAPHQL = 'graphQL',
  RXJS = 'RxJS',
  ANGULAR1 = 'Angular',
  JAVASCRIPT1 = 'Javascript',
  GRAPHQL1 = 'graphQL',
  RXJS1 = 'RxJS',
  ANGULAR2 = 'Angular',
  JAVASCRIPT2 = 'Javascript',
  GRAPHQL2 = 'graphQL',
  RXJS2 = 'RxJS',
  ANGULAR3 = 'Angular',
  JAVASCRIP3T = 'Javascript',
  GRAPHQ3L = 'graphQL',
  RXJS3 = 'RxJS',
}
